'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {criar,renderHtml}=require('../js/edr-v2-entrada-plano.js');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const copy=x=>JSON.parse(JSON.stringify(x));
function snapshot(){return {company_id:id(1),obra_id:id(3),plano:{revisao:1,delivery:'2026-10-30',stage:'confirmed',contrato_entrada:100000},rows:[{id:id(4),label:'Parcela sintética',base:100000,mode:'percent',rate:1500,final:0,due:'2026-11-10',method:'Pix',version:1,total:107500,principalDue:100000,additionDue:15000,received:50000,principalRemaining:50000,additionRemaining:7500,cancelled:7500,remaining:57500}],receipts:[],requests:[],history:[],permissions:{solicitar:true,receber:true,aprovar:false},contas:[],repasses_disponiveis:[],totals:{original:100000,agreed:107500,received:50000,remaining:57500,cancelled:7500,unlinked:0}};}
function setup(options={}){const storage=options.storage||new Map(),writes=[];let identity={company:id(1),actor:id(2),obra:id(3),perfil:'admin'},state=snapshot(),onRpc;
 const deps={identidade:()=>identity,storage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},uuid:()=>id(80),rpc:async(fn,p)=>{writes.push({fn,p:copy(p)});if(onRpc){const result=await onRpc(fn,p);if(result)return result;}return {ok:true,dados:fn==='entrada_plano_operar'?{...copy(state),operacao_id:p.p_operacao}:copy(state)};},recarregar:async()=>{}};
 return {api:criar(deps),storage,writes,deps,state,vary:i=>identity=i,rpc:fn=>onRpc=fn};}
test('retorno confirmado remove intenção e atualiza snapshot uma vez',async()=>{const e=setup();await e.api.carregar();const s=await e.api.operar({tipo:'receber',revisao:1,amount:10});assert.equal(s.operacao_id,id(80));assert.equal(e.storage.size,0);assert.equal(e.writes.filter(x=>x.fn==='entrada_plano_operar').length,1);});
test('falha incerta sobrevive novo controller e reenvia mesmo UUID/payload',async()=>{const e=setup();await e.api.carregar();e.rpc(async fn=>fn==='entrada_plano_operar'?{ok:false,incerto:true,mensagem:'Resposta perdida'}:null);const pedido={tipo:'receber',revisao:1,amount:10,date:'2026-10-20'};await assert.rejects(e.api.operar(pedido),{incerto:true});const saved=copy(e.api.pending());await assert.rejects(e.api.operar(pedido),/pendente/);const novo=setup({storage:e.storage});await novo.api.carregar();await novo.api.recuperar();const write=novo.writes.find(x=>x.fn==='entrada_plano_operar');assert.equal(write.p.p_operacao,saved.operacao);assert.deepEqual(write.p.p_pedido,pedido);assert.equal(novo.storage.size,0);});
test('falha comprovada libera journal, preservando snapshot vigente',async()=>{const e=setup();await e.api.carregar();e.rpc(async fn=>fn==='entrada_plano_operar'?{ok:false,incerto:false,mensagem:'Versão obsoleta'}:null);await assert.rejects(e.api.operar({tipo:'receber'}),/obsoleta/);assert.equal(e.storage.size,0);assert.equal(e.api.estado().plano.revisao,1);});
test('resposta sem operação confirmada conserva journal',async()=>{const e=setup();await e.api.carregar();e.rpc(async fn=>fn==='entrada_plano_operar'?{ok:true,dados:snapshot()}:null);await assert.rejects(e.api.operar({tipo:'receber'}),{incerto:true});assert.ok(e.api.pending());});
test('troca empresa ignora resposta antiga e impede replay em outro tenant',async()=>{const e=setup();let release;e.rpc(()=>new Promise(r=>release=r));const promise=e.api.carregar();e.vary({company:id(10),actor:id(2),obra:id(3),perfil:'admin'});release({ok:true,dados:snapshot()});assert.equal(await promise,null);assert.equal(e.api.estado(),null);assert.equal(e.api.pending(),null);});
test('troca obra no meio da escrita ignora estado mas conserva intenção original',async()=>{const e=setup();await e.api.carregar();let release;e.rpc(()=>new Promise(r=>release=r));const promise=e.api.operar({tipo:'receber'});e.vary({company:id(1),actor:id(2),obra:id(50),perfil:'admin'});release({ok:true,dados:{...snapshot(),operacao_id:id(80)}});assert.deepEqual(await promise,{obsoleto:true});assert.equal(e.api.estado(),null);assert.equal(e.storage.size,1);});
test('concorrência local bloqueia segundo envio e preserva primeira intenção',async()=>{const e=setup();await e.api.carregar();let release;e.rpc(fn=>fn==='entrada_plano_operar'?new Promise(r=>release=r):null);const first=e.api.operar({tipo:'receber'});await assert.rejects(e.api.operar({tipo:'receber'}),/andamento/);release({ok:true,dados:{...snapshot(),operacao_id:id(80)}});await first;assert.equal(e.writes.filter(x=>x.fn==='entrada_plano_operar').length,1);});
test('journal sem persistência impede envio financeiro',async()=>{const e=setup();e.deps.storage.setItem=()=>{};await e.api.carregar();await assert.rejects(e.api.operar({tipo:'receber'}),/guardar a chave/);assert.equal(e.writes.length,1);});
test('permissão é usada do snapshot, nome exibido não habilita aprovação',async()=>{const e=setup();await e.api.carregar();await assert.rejects(e.api.operar({tipo:'decidir'}),/permissão/);assert.equal(e.writes.length,1);});
test('nova leitura falha retira números anteriores',async()=>{const e=setup();await e.api.carregar();e.rpc(async()=>({ok:false,mensagem:'Falhou'}));assert.equal(await e.api.carregar(),null);assert.equal(e.api.estado(),null);assert.match(e.api.erro(),/Falhou/);});
test('totais renderizados não descontam cancelamento duas vezes',()=>{const h=renderHtml(snapshot());assert.match(h,/Final vigente<\/span><strong>R\$\s1075|Final vigente<\/span><strong>R\$\s1\.075,00/);assert.match(h,/R\$\s575,00/);assert.doesNotMatch(h,/1\.000,00<\/strong><\/div><div class="plan-metric"><span>Recebido/);});
test('sem plano mostra contrato e recebimentos atuais, com aviso de vínculo',()=>{const s=snapshot();s.rows=[];s.plano.stage='draft';s.plano.contrato_entrada=100000;s.totals={original:0,agreed:0,received:50000,unlinked:50000,cancelled:0};const h=renderHtml(s);assert.match(h,/Solicitação inicial aguardando aprovação/);assert.match(h,/R\$\s1\.000,00/);assert.match(h,/já recebidos aguardam vínculo/);assert.doesNotMatch(h,/Versão vigente/);});
test('conteúdo textual do servidor é escapado e não cria controle de identidade',()=>{const s=snapshot();s.rows[0].label='<img src=x onerror=alert(1)>';const h=renderHtml(s);assert.ok(h.includes('&lt;img'));assert.ok(!h.includes('<img'));assert.doesNotMatch(h,/plan-actor|sampleDates|Simular|Restaurar plano/);});
test('avisos são dados a configurar, datas ausentes não inventam calendário',()=>{const s=snapshot();s.rows[0].due=null;s.plano.delivery=null;const h=renderHtml(s);assert.match(h,/A configurar/);assert.match(h,/Aguardando data/);assert.match(h,/automação não está ativa/);assert.doesNotMatch(h,/class="plan-reminder"/);});

test('replay confirma UUID antigo, mas publica revisão mais recente',async()=>{const e=setup();await e.api.carregar();e.rpc(async fn=>fn==='entrada_plano_operar'?{ok:false,incerto:true,mensagem:'Resposta perdida'}:null);await assert.rejects(e.api.operar({tipo:'receber'}));e.state.plano.revisao=5;e.rpc(async fn=>fn==='entrada_plano_operar'?{ok:true,dados:{...snapshot(),operacao_id:id(80)}}:null);const result=await e.api.recuperar();assert.equal(result.confirmado,true);assert.equal(e.api.estado().plano.revisao,5);assert.equal(e.storage.size,0);});
test('commit confirmado e leitura posterior falha: sem journal nem saldo antigo',async()=>{const e=setup();await e.api.carregar();e.rpc(async(fn,p)=>fn==='entrada_plano_operar'?{ok:true,dados:{...snapshot(),operacao_id:p.p_operacao}}:{ok:false,mensagem:'Consulta indisponível'});const result=await e.api.operar({tipo:'receber'});assert.equal(result.confirmado,true);assert.equal(e.api.estado(),null);assert.equal(e.api.pending(),null);assert.match(e.api.erro(),/Operação confirmada/);});

test('Caixa não aberto: orienta Banco/Dinheiro, bloqueia dinheiro novo/estorno e mantém vínculo',()=>{const s=snapshot();s.repasses_disponiveis=[{id:id(8),amount:50000,date:'2026-09-16'}];s.receipts=[{id:id(77),rowId:id(4),amount:10000,available:10000,date:'2026-09-17',method:'Pix'}];const h=renderHtml(s);assert.match(h,/Declare a abertura de Banco e Dinheiro no Caixa antes de registrar novos recebimentos\/estornos/);assert.match(h,/data-ep-action="receber"[^>]* disabled/);assert.match(h,/data-ep-action="estorno"[^>]* disabled/);assert.match(h,/data-ep-action="vincular"[^>]*>Vincular existente/);assert.doesNotMatch(h,/data-ep-action="vincular"[^>]* disabled/);const hidden=structuredClone(s);hidden.permissions={solicitar:false,receber:false,aprovar:false};assert.doesNotMatch(renderHtml(hidden),/Declare a abertura/);});

test('histórico do contrato RPC real traduz operações e distingue decisão/estorno',()=>{const s=snapshot();s.requests=[{id:id(51),kind:'terms',status:'approved'},{id:id(52),kind:'reversal',status:'approved'},{id:id(53),kind:'reversal',status:'rejected'}];s.history=[{type:'solicitar'},{type:'solicitar_estorno'},{type:'receber'},{type:'vincular'},{type:'decidir',requestId:id(51)},{type:'decidir',requestId:id(52)},{type:'decidir',requestId:id(53)}];const h=renderHtml(s);for(const title of ['Solicitação de alteração','Solicitação de estorno','Recebimento confirmado','Recebimento existente vinculado','Solicitação aprovada','Estorno aprovado','Estorno rejeitado'])assert.ok(h.includes('<strong>'+title+'</strong>'),title);assert.doesNotMatch(h,/<strong>(solicitar|solicitar_estorno|receber|vincular|decidir)<\/strong>/);});
