'use strict';
// Chromium novo, index/CSS/modulos reais, transporte e identidade somente sintéticos.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.EDR_PLAYWRIGHT_MODULE||'playwright');
const C=require('../js/edr-v2-entrada-plano-calc.js');
const raiz=path.resolve(__dirname,'..'),origin='http://127.0.0.1:43783',id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
let browser;
test.before(async()=>{browser=await chromium.launch({headless:true,executablePath:process.env.EDR_CHROMIUM_EXECUTABLE||undefined});});
test.after(async()=>{await browser?.close();});
function fixture(){const rows=[{id:id(4),label:'Parcela sintética maio',base:100000,mode:'waived',rate:0,final:0,due:null,method:'A combinar',version:1},{id:id(5),label:'Parcela sintética novembro',base:100000,mode:'percent',rate:1500,final:0,due:'2026-11-15',method:'Pix',version:1}];return {company_id:id(1),obra_id:id(3),plano:{revisao:1,stage:'confirmed',delivery:'2026-10-30',contrato_entrada:200000},rows:rows.map(r=>({...r,...C.components(r,[])})),receipts:[],requests:[],history:[],repasses_disponiveis:[],permissions:{solicitar:true,receber:true,aprovar:false},contas:[{id:id(9),codigo:'banco',nome:'Banco sintético',corte_em:'2026-10-08T15:00:00Z',fuso:'America/Sao_Paulo'},{id:id(10),codigo:'dinheiro',nome:'Dinheiro sintético',corte_em:'2026-10-08T15:00:00Z',fuso:'America/Sao_Paulo'}],totals:{original:200000,agreed:215000,received:0,remaining:215000,unlinked:0,cancelled:0}};}
function fixtureVinculo(){const s=fixture();s.repasses_disponiveis=[{id:id(8),amount:50000,date:'2026-09-16',tipo:'entrada'}];s.totals.received=50000;s.totals.unlinked=50000;s.totals.remaining=165000;return s;}
function html(dados){
  const bootstrap='window.__epQa='+JSON.stringify({state:dados,writes:[],reads:[],fail:null}).replace(/</g,'\\u003c')+';'+String.raw`
    _companyId=__epQa.state.company_id;_supabaseToken='SENTINELA_SINTETICA';Object.assign(usuarioAtual,{id:'00000000-0000-4000-8000-000000000002',nome:'Pessoa sintética',perfil:'admin'});
    sbRpcEntradaPlano=async(fn,p)=>{const q=__epQa;if(fn==='entrada_plano_estado'){q.reads.push(p);return q.fail==='read'?{ok:false,mensagem:'Falha sintética'}:{ok:true,dados:JSON.parse(JSON.stringify(q.state))};}q.writes.push(JSON.parse(JSON.stringify(p)));if(q.fail==='uncertain'){q.fail=null;return {ok:false,incerto:true,mensagem:'Resposta perdida sintética'};}if(q.fail==='rejected')return {ok:false,incerto:false,mensagem:'Versão obsoleta sintética'};return {ok:true,dados:{...JSON.parse(JSON.stringify(q.state)),operacao_id:p.p_operacao}};};
    sbRpcEstoque=async()=>({ok:true,dados:{company_id:_companyId,planos:[]}});
    loadRepassesCef=async()=>{};loadDistribuicoes=async()=>{};loadLancamentos=async()=>{};showToast=()=>{};
    window.populateSelects=()=>{};
    window.addEventListener('DOMContentLoaded',()=>{document.getElementById('login-screen').style.display='none';document.getElementById('app-shell').style.display='';document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById('view-obras').classList.add('active');document.getElementById('header-title').textContent='Obras · ensaio sintético';obras=[{id:__epQa.state.obra_id,company_id:_companyId,nome:'CASA SINTÉTICA QA',contrato_entrada:2000}];ObrasModule.obraAberta=__epQa.state.obra_id;document.getElementById('obras-cards-overview').style.display='none';document.getElementById('obras-sticky').style.display='';obrasSwitchTab('entrada');});
  `;
  return fs.readFileSync(path.join(raiz,'index.html'),'utf8').replace(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi,(tag,attrs,conteudo)=>{const src=/\bsrc=["']([^"']+)["']/.exec(attrs)?.[1];if(!src){const end=conteudo.indexOf('// fecharModal');return conteudo.includes('// Mesmo build do cache publicado')&&end>0?'<script>'+conteudo.slice(0,end)+'</script>':'';}const file=src.split('?')[0];if(!/^js\/edr-v2-(infra|utils-extras|entrada-cliente|entrada-plano|entrada-plano-calc|entrada-plano-projecoes|obras|custos)\.js$/.test(file))return '';return file==='js/edr-v2-infra.js'?tag+'<script>'+bootstrap+'</script>':tag;});
}
async function abrir(dados=fixture(),width=1440){const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block'}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(5000);
  await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(url.origin!==origin||request.method()!=='GET'){if(/supabase\.co$/.test(url.hostname))external.push(url.pathname);return route.abort('blockedbyclient');}if(url.pathname==='/index.html')return route.fulfill({contentType:'text/html; charset=utf-8',body:html(dados)});const file=path.resolve(raiz,'.'+decodeURIComponent(url.pathname)),relative=path.relative(raiz,file);if(relative.startsWith('..')||path.isAbsolute(relative)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream',body:fs.readFileSync(file)});});
  await page.goto(origin+'/index.html');try{await page.locator('.entrada-plano .plan-table').waitFor();}catch(e){throw Error(e.message+' · '+JSON.stringify(errors));}return {page,context,errors,external,close:()=>context.close()};
}
const content=page=>page.locator('#entrada-plano-content');
async function submit(page){await page.locator('#ep-motivo').fill('Motivo sintético confirmado');await page.locator('#ep-submit').click();await page.waitForFunction(()=>__epQa.writes.length>0);}
async function screenshot(page,name){if(!process.env.EDR_ENTRADA_EVIDENCE_DIR)return;const dir=path.resolve(process.env.EDR_ENTRADA_EVIDENCE_DIR);fs.mkdirSync(dir,{recursive:true});await page.evaluate(()=>scrollTo(0,0));const dialog=await page.locator('#entrada-plano-modal.active').count();await page.screenshot({path:path.join(dir,name+'.png'),fullPage:!dialog});}
test('desktop: aba real, calendário indefinido, vínculo ID e CSS v6',async()=>{const a=await abrir(fixtureVinculo());try{assert.equal(await content(a.page).locator('.plan-table tbody tr').count(),2);assert.match(await content(a.page).innerText(),/Aguardando data/);assert.match(await content(a.page).innerText(),/R\$\s500,00/);await screenshot(a.page,'entrada-desktop');await content(a.page).locator('[data-ep-action="vincular"]').first().click();assert.equal(await a.page.locator('#ep-repasse option').count(),2);assert.match(await a.page.locator('#ep-repasse').innerText(),/500,00.*16\/09\/2026/);await a.page.locator('#ep-repasse').selectOption(id(8));await submit(a.page);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.tipo,'vincular');assert.equal(p.repasse_id,id(8));assert.equal(p.row_id,id(4));assert.equal(p.amount,undefined);assert.deepEqual(a.errors,[]);assert.deepEqual(a.external,[]);}finally{await a.close();}});
test('editor: percentual exclusivo/final zero/datas sem seed e motivo persistido',async()=>{const a=await abrir();try{await content(a.page).locator('[data-ep-action="planejar"]').click();assert.equal(await a.page.locator('#ep-due-0').inputValue(),'');assert.equal(await a.page.locator('#ep-rate-0').isVisible(),false);assert.match(await a.page.locator('#ep-preview').innerText(),/2\.150,00/);await a.page.locator('#ep-mode-1').selectOption('final');await a.page.locator('#ep-final-1').fill('0,00');assert.equal(await a.page.locator('#ep-rate-1').isVisible(),false);await a.page.locator('#ep-due-1').fill('');await screenshot(a.page,'entrada-editor-desktop');await submit(a.page);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.rows[0].final,0);assert.equal(p.rows[1].final,0);assert.equal(p.rows[1].rate,0);assert.equal(p.rows[0].due,null);assert.equal(p.rows[1].due,null);assert.equal(p.delivery,'2026-10-30');assert.equal(p.actor,undefined);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('editor: adicionar/remover parcela vazia e sugestão 15% somente após entrega',async()=>{const a=await abrir();try{await content(a.page).locator('[data-ep-action="planejar"]').click();assert.equal(await a.page.locator('[data-ep-action="sugestao"][data-ep-id="0"]').isDisabled(),true);await a.page.locator('#ep-due-0').fill('2026-10-30');assert.equal(await a.page.locator('[data-ep-action="sugestao"][data-ep-id="0"]').isDisabled(),true);await a.page.locator('#ep-due-0').fill('2026-10-31');await a.page.locator('[data-ep-action="sugestao"][data-ep-id="0"]').click();assert.equal(await a.page.locator('#ep-rate-0').inputValue(),'15,00');await a.page.locator('[data-ep-action="adicionar"]').click();assert.equal(await a.page.locator('.plan-editor-row').count(),3);await a.page.locator('[data-ep-action="remover"][data-ep-id="2"]').click();assert.equal(await a.page.locator('.plan-editor-row').count(),2);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('recebimento parcial antecipado: cálculo real separado e corte obrigatório',async()=>{const a=await abrir();try{await content(a.page).locator('[data-ep-action="receber"]').nth(1).click();assert.equal(await a.page.locator('#ep-data').inputValue(),'');await a.page.locator('#ep-amount').fill('500,00');await a.page.locator('#ep-data').fill('2026-10-08');await a.page.locator('#ep-conta').selectOption(id(9));assert.match(await a.page.locator('#ep-preview').innerText(),/Acréscimo cancelado\s+R\$\s75,00/);await a.page.locator('#ep-motivo').fill('Pagamento sintético');await a.page.locator('#ep-submit').click();assert.match(await a.page.locator('#ep-error').innerText(),/dia do corte/);assert.equal(await a.page.evaluate(()=>__epQa.writes.length),0);await a.page.locator('#ep-corte').selectOption('apos_corte');await screenshot(a.page,'entrada-recebimento-desktop');await a.page.locator('#ep-submit').click();await a.page.waitForFunction(()=>__epQa.writes.length===1);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.amount,50000);assert.equal(p.conta_id,id(9));assert.equal(p.decisao_corte,'apos_corte');assert.equal(p.date,'2026-10-08');assert.equal(p.cancelled,undefined);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('pedido incerto: reload preserva intenção e repetir usa mesmo UUID',async()=>{const a=await abrir(fixtureVinculo());try{await a.page.evaluate(()=>__epQa.fail='uncertain');await content(a.page).locator('[data-ep-action="vincular"]').first().click();await a.page.locator('#ep-repasse').selectOption(id(8));await submit(a.page);await a.page.locator('#ep-error [data-ep-action="recuperar"]').waitFor();const first=await a.page.evaluate(()=>__epQa.writes[0]);await a.page.reload();await content(a.page).locator('[data-ep-action="recuperar"]').waitFor();await content(a.page).locator('[data-ep-action="recuperar"]').click();await a.page.waitForFunction(()=>__epQa.writes.length===1);const second=await a.page.evaluate(()=>__epQa.writes[0]);assert.deepEqual(second,first);assert.equal(await content(a.page).locator('[data-ep-action="recuperar"]').count(),0);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('permissões do servidor: Duam decide; outro usuário não opera por nome',async()=>{const s=fixture();s.permissions={solicitar:false,receber:false,aprovar:true};s.requests=[{id:id(55),kind:'plan',status:'pending',actor:id(2),why:'Motivo sintético',at:'2026-10-08T15:00:00Z',before:{rows:s.rows,delivery:s.plano.delivery},after:{rows:s.rows,delivery:null}}];const a=await abrir(s);try{assert.equal(await content(a.page).locator('[data-ep-action="receber"]').first().isDisabled(),true);assert.equal(await content(a.page).locator('[data-ep-action="planejar"]').isDisabled(),true);await content(a.page).locator('[data-ep-action="aprovar"]').click();await submit(a.page);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.tipo,'decidir');assert.equal(p.proposta_id,id(55));assert.equal(p.decisao,'approved');assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('estorno parcial: valor e recomposição do acréscimo visíveis; solicitação não decide',async()=>{const s=fixture();const receipt={id:id(77),rowId:id(5),amount:50000,principal:50000,additionPaid:0,cancelled:7500,date:'2026-10-09',method:'Pix',available:50000,movimento_id:id(90)};s.receipts=[receipt];s.rows=s.rows.map(r=>({...r,...C.components(r,s.receipts)}));s.totals={original:200000,agreed:207500,received:50000,remaining:157500,cancelled:7500,unlinked:0};const a=await abrir(s);try{await content(a.page).locator('[data-ep-action="estorno"]').click();await a.page.locator('#ep-amount').fill('250,00');await a.page.locator('#ep-data').fill('2026-10-10');await a.page.locator('#ep-conta').selectOption(id(10));assert.match(await a.page.locator('#ep-preview').innerText(),/Acréscimo cancelado a restabelecer\s+R\$\s37,50/);await submit(a.page);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.tipo,'solicitar_estorno');assert.equal(p.amount,25000);assert.equal(p.receipt_id,id(77));assert.equal(p.decisao,undefined);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
for(const width of [390,320])test('celular '+width+'px: tabela responsiva, moedas e formulário sem overflow',async()=>{const a=await abrir(fixture(),width);try{const bounds=await a.page.evaluate(()=>({w:innerWidth,doc:document.documentElement.scrollWidth,root:document.getElementById('entrada-plano-content').scrollWidth,client:document.getElementById('entrada-plano-content').clientWidth,over:[...document.querySelectorAll('body *')].filter(x=>x.getClientRects().length&&x.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(x=>({tag:x.tagName,id:x.id,cl:x.className,right:x.getBoundingClientRect().right}))}));assert.ok(bounds.doc<=width+1,JSON.stringify(bounds));assert.ok(bounds.root<=bounds.client+1,JSON.stringify(bounds));await screenshot(a.page,'entrada-mobile-'+width);await content(a.page).locator('[data-ep-action="planejar"]').click();const modalBounds=await a.page.locator('.plan-modal-box').boundingBox();assert.ok(modalBounds.x>=0&&modalBounds.x+modalBounds.width<=width);await screenshot(a.page,'entrada-editor-mobile-'+width);await a.page.locator('#ep-submit').focus();await a.page.keyboard.press('Tab');assert.equal(await a.page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Fechar formulário');assert.deepEqual(a.errors,[]);}finally{await a.close();}});

test('plano inicial: original real aparece e nova parcela não recebe data nem taxa automática',async()=>{const s=fixture();s.rows=[];s.plano.stage='none';s.plano.revisao=0;s.plano.delivery=null;s.totals={original:0,agreed:0,received:0,remaining:0,unlinked:0,cancelled:0};const a=await abrir(s);try{assert.match(await content(a.page).innerText(),/R\$\s2\.000,00/);await content(a.page).locator('[data-ep-action="planejar"]').click();await a.page.locator('[data-ep-action="adicionar"]').click();await a.page.locator('#ep-label-0').fill('Entrada inicial sintética');await a.page.locator('#ep-base-0').fill('2000,00');assert.equal(await a.page.locator('#ep-due-0').inputValue(),'');assert.equal(await a.page.locator('#ep-delivery').inputValue(),'');assert.equal(await a.page.locator('#ep-mode-0').inputValue(),'waived');await submit(a.page);const p=await a.page.evaluate(()=>__epQa.writes[0].p_pedido);assert.equal(p.rows[0].base,200000);assert.equal(p.rows[0].rate,0);assert.equal(p.rows[0].due,null);assert.equal(p.delivery,null);assert.match(p.rows[0].id,/^[0-9a-f-]{36}$/);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('rotas legadas: entrada ativa não edita/exclui; PLS continua disponível',async()=>{const a=await abrir();try{const result=await a.page.evaluate(async({obra,entrada,pls})=>{const avisos=[];showToast=x=>avisos.push(x);CustosModule.repassesCef=[{id:entrada,obra_id:obra,tipo:'entrada',valor:500},{id:pls,obra_id:obra,tipo:'pls',valor:100}];let deleted=0,opened=0;sbDelete=async()=>{deleted++;return 1;};custosAbrirModalRepasse=()=>opened++;await custosEditarRepasse(entrada);await custosExcluirRepasse(entrada);await custosEditarRepasse(pls);return{deleted,opened,avisos};},{obra:id(3),entrada:id(8),pls:id(90)});assert.equal(result.deleted,0);assert.equal(result.opened,1);assert.equal(result.avisos.length,2);assert.match(result.avisos[0],/plano ativo/);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
test('build visível coincide com CACHE_NAME consultado pelo código real do index',async()=>{const a=await abrir();try{await a.page.waitForFunction(()=>document.getElementById('edr-build-badge')?.textContent.includes('edr-'));const expected=/const\s+CACHE_NAME\s*=\s*['"]([^'"]+)['"]/.exec(fs.readFileSync(path.join(raiz,'sw.js'),'utf8'))[1];assert.equal(await a.page.locator('#edr-build-badge').textContent(),'EDR v2 · '+expected);assert.deepEqual(a.errors,[]);assert.deepEqual(a.external,[]);}finally{await a.close();}});

test('CEF: consulta do plano falha e valor pendente mostra indisponível',async()=>{const a=await abrir();try{await a.page.evaluate(async()=>{EntradaPlanoProjecoes.invalidar();sbRpcEstoque=async()=>({ok:false,mensagem:'Leitura sintética indisponível'});await renderObraCef();obrasSwitchTab('cef');});const card=a.page.locator('#obras-cef-content .cef-card').filter({hasText:'Entrada · consulta indisponível'});assert.equal(await card.count(),1);assert.equal(await card.locator('.cef-card-value').innerText(),'Indisponível');assert.match(await card.innerText(),/2\.000,00 original/);assert.deepEqual(a.errors,[]);}finally{await a.close();}});

test('Caixa não aberto: formulário não abre por chamada direta e vínculo existente continua acessível',async()=>{const s=fixtureVinculo();s.contas=[];s.receipts=[{id:id(77),rowId:id(5),amount:10000,principal:10000,additionPaid:0,cancelled:0,date:'2026-09-17',method:'Pix',available:10000,movimento_id:id(90)}];const a=await abrir(s);try{assert.match(await content(a.page).innerText(),/Declare a abertura de Banco e Dinheiro no Caixa antes de registrar novos recebimentos\/estornos/);assert.equal(await content(a.page).locator('[data-ep-action="receber"]').first().isDisabled(),true);assert.equal(await content(a.page).locator('[data-ep-action="estorno"]').isDisabled(),true);await a.page.evaluate(({row,receipt})=>{EntradaPlano.abrir('receber',row);EntradaPlano.abrir('estorno',receipt);},{row:id(5),receipt:id(77)});assert.equal(await a.page.locator('#entrada-plano-modal').isVisible(),false);assert.equal(await a.page.evaluate(()=>__epQa.writes.length),0);await content(a.page).locator('[data-ep-action="vincular"]').first().click();assert.equal(await a.page.locator('#ep-repasse').isVisible(),true);assert.equal(await a.page.locator('#ep-conta').count(),0);assert.deepEqual(a.errors,[]);}finally{await a.close();}});
